-- ============================================================================
-- Grand Test Script for MGD_LNP_PK Package
-- Registration: XWM00003001200
--
-- Inserts test data into ALL tables so that every stored procedure in
-- MGD_LNP_PK returns data with all applicable charge codes.
--
-- IMPORTANT: All dates are set within the MGD period window which is derived
-- from paye_data.safe_lp_sequence. Currently: 01-OCT-2013 to 31-DEC-2014.
-- If the period window changes, charge_date / payment_post_date /
-- reallocation_date values may need adjusting.
--
-- Tables populated:
--   1. MGD_OPERATOR_DETAILS   (getMGDOperatorDetails)
--   2. MGD_LP_TOTAL           (14 sprocs use totals)
--   3. MGD_LP_CHARGE          (C-type: all 6 codes, I-type: all 6 codes, R-type: all 6 codes)
--   4. MGD_LP_ACCRUING_INTEREST (getMGDAccruingDrilldown, getMGDInterestAccruingDetails)
--   5. MGD_LP_LATE_PAY_INTEREST (getMGDInterestDetails, getMGDInterestDrilldown)
--   6. MGD_LP_PAYMENT           (getMGDPayments, getMGDReallocationsInDetails)
--   7. MGD_LP_PAYMENT_ON_ACCOUNT (getMGDPayments, getMGDReallocationsInDetails)
--   8. MGD_LP_REALLOCATION_OUT   (getMGDActualRepayments, getMGDReallocationsOutDetails,
--                                  getMGDRepaymentInterestRepaid)
--   9. MGD_RETURN_DETAILS        (getMGDCurrentPosition)
--
-- Charge codes covered (SAFE_MTRANS_CODE):
--   1940 - PPLR interest bearing
--   1950 - Return Charge
--   1960 - Central Assessment
--   1970 - Officer Assessment
--   1980 - Late Filing Penalty
--   1990 - Late Payment Penalty
--
-- Safe to run multiple times — deletes all existing data first, then inserts.
-- ============================================================================

SET DEFINE OFF;

-- ============================================================================
-- 0. CLEAN SLATE — Delete all existing data for XWM00003001200
--    Order matters: delete from child tables first to avoid FK issues.
-- ============================================================================
DELETE FROM mgd_lp_accruing_interest WHERE mgd_reg_number = 'XWM00003001200';
DELETE FROM mgd_lp_late_pay_interest WHERE mgd_reg_number = 'XWM00003001200';
DELETE FROM mgd_lp_payment WHERE mgd_reg_number = 'XWM00003001200';
DELETE FROM mgd_lp_payment_on_account WHERE mgd_reg_number = 'XWM00003001200';
DELETE FROM mgd_lp_reallocation_out WHERE mgd_reg_number = 'XWM00003001200';
DELETE FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200';
DELETE FROM mgd_lp_total WHERE mgd_reg_number = 'XWM00003001200';
DELETE FROM mgd_return_details WHERE mgd_reg_number = 'XWM00003001200';
DELETE FROM mgd_operator_details WHERE mgd_reg_number = 'XWM00003001200';
COMMIT;

-- ============================================================================
-- 1. MGD_OPERATOR_DETAILS
--    Used by: getMGDOperatorDetails, getMGDAccountOverview (existence check)
-- ============================================================================
INSERT INTO mgd_operator_details (
    MGD_REG_NUMBER, BUSINESS_PARTNER_NUMBER, SOLE_PROP_TITLE, SOLE_PROP_FIRST_NAME,
    SOLE_PROP_MIDDLE_NAME, SOLE_PROP_LAST_NAME, BUSINESS_NAME, BUS_ADDRESS_1,
    BUS_ADDRESS_2, BUS_ADDRESS_3, BUS_ADDRESS_4, BUS_POSTCODE, BUS_COUNTRY, BUS_ADI,
    BUS_IOM_OR_CI, BUS_PHONE_NUMBER, BUS_MOBILE_PHONE_NUMBER, BUS_FAX_NUMBER,
    BUS_EMAIL_ADDR, TRADING_NAME, TYPE_OF_BUSINESS, TRADE_CLASS, BUS_ACT_DESCRIPTION,
    VRN, NINO, UTR, CRN, DATE_OF_BIRTH, REGISTRATION_DATE, DATE_OF_DEREGISTRATION,
    REASON_OF_DEREGISTRATION, SEASONAL_BUSINESS, UK_INCORPORATED_FLAG,
    DATE_OF_INCORPORATION, COUNTRY_OF_INCORPORATION, FOREIGN_CORPORATE_REF,
    CORRES_NAME1, CORRES_NAME2, CORRES_ADDRESS_1, CORRES_ADDRESS_2, CORRES_ADDRESS_3,
    CORRES_ADDRESS_4, CORRES_POSTCODE, CORRES_COUNTRY, CORRES_ADI, CORRES_IOM_OR_CI,
    CORRES_PHONE_NUMBER, CORRES_MOBILE_PHONE_NUMBER, CORRES_FAX_NUMBER,
    CORRES_EMAIL_ADDR, AGENT_OWN_REF, MGD_AGENT_REF, PERIOD_TYPE, RETURN_PERIOD_ID,
    FIRST_RETURN_PERIOD_END_DATE, NO_OF_MACHINES, NON_STD_PERIOD_1_END_DATE,
    NON_STD_PERIOD_2_END_DATE, NON_STD_PERIOD_3_END_DATE, NON_STD_PERIOD_4_END_DATE,
    NON_STD_PERIOD_5_END_DATE, NON_STD_PERIOD_6_END_DATE, NON_STD_PERIOD_7_END_DATE,
    NON_STD_PERIOD_8_END_DATE, MGDREF_OF_NEW_GROUP, ENROLLED_SIG, RECORD_UPDATED
)
SELECT 'XWM00003001200', '0100099001', 'Mr', 'Test', 'M', 'User',
       'Test Business Ltd', '1 Test Street', 'Test Town', 'Test County', null,
       'TE1 1ST', null, 'Test ADI', 'N', '01234 567890', '07979 123456',
       '01234 567891', 'test@test.com', 'Test Trading', 'Corporate Body',
       null, null, null, null, null, 'CR123456', TO_TIMESTAMP('01-JAN-80','DD-MON-RR HH24.MI.SSXFF'),
       TO_TIMESTAMP('01-FEB-13','DD-MON-RR HH24.MI.SSXFF'), null, null, 'N', 'Y',
       TO_TIMESTAMP('01-JAN-80','DD-MON-RR HH24.MI.SSXFF'), null, null,
       'Corres Name1', 'Corres Name2', 'Corres Addr 1', 'Corres Addr 2',
       'Corres Addr 3', null, 'CO1 1RR', null, 'Corres ADI', null,
       '01234 111111', '07979 222222', '01234 333333', 'corres@test.com',
       'AGT/REF/001', null, 'S', 1, null, 10,
       null, null, null, null, null, null, null, null, null, null,
       TO_TIMESTAMP('01-MAR-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM mgd_operator_details WHERE mgd_reg_number = 'XWM00003001200');


-- ============================================================================
-- 2. MGD_LP_TOTAL
-- ============================================================================
INSERT INTO mgd_lp_total (
    MGD_REG_NUMBER, BALANCE_BROUGHT_FORWARD, RETURN_CHARGE_AMOUNT,
    CENTRAL_ASSESSMENT_AMOUNT, SUBTOTAL_RETURNS, TOTAL_PENALTY_AMOUNT,
    TOTAL_ADJUSTMENT_AMOUNT, TOTAL_REALLOCATION_IN, TOTAL_REALLOCATION_OUT,
    TOTAL_REALLOCATION, OFFICER_ASSESSMENT_AMOUNT, TOTAL_LATE_PAY_INTEREST,
    TOTAL_REPAY_INTEREST, TOTAL_INTEREST, SUBTOTAL_OTHERS,
    TOTAL_ALLOCATED_PAYMENTS, TOTAL_PAY_ON_ACCOUNT, TOTAL_PAYMENTS,
    TOTAL_ACTUAL_REPAYMENTS, TOTAL_RRI, TOTAL_REPAYMENTS,
    TOTAL_AMOUNT_DUE, RECORD_UPDATED, SUBTOTAL_PAYMENTS
)
SELECT 'XWM00003001200',
       5000, 8500, 4950, 13450, 650, 100, 500, -300, 200, 2000,
       150, 75, 225, 2875, 3000, 500, 3500, -200, -50, -250,
       18000, TO_TIMESTAMP('24-MAR-16','DD-MON-RR HH24.MI.SSXFF'), 4000
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_total WHERE mgd_reg_number = 'XWM00003001200');


-- ============================================================================
-- 3a. MGD_LP_CHARGE - C-type (Charge) rows for all 6 charge codes
--     Dates within period window (01-OCT-2013 onwards)
-- ============================================================================

-- 1940 - PPLR interest bearing (interest_flag=4, interest-bearing for accruing interest)
INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C01', 1, TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'C', 1940, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 1240, null, 3000, 0, 4, TO_TIMESTAMP('31-JAN-14','DD-MON-RR HH24.MI.SSXFF'), null, null, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C01' AND tie_breaker = 1);

-- 1950 - Return Charge (C-type) period 1
INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C02', 1, TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'C', 1950, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 1240, null, 4500, 0, 4, TO_TIMESTAMP('31-JAN-14','DD-MON-RR HH24.MI.SSXFF'), null, null, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C02' AND tie_breaker = 1);

-- 1950 - Return Charge (C-type) period 2
INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C03', 1, TO_TIMESTAMP('01-JAN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-MAR-14','DD-MON-RR HH24.MI.SSXFF'), 'C', 1950, TO_TIMESTAMP('15-MAR-14','DD-MON-RR HH24.MI.SSXFF'), 1240, null, 4000, 0, 4, TO_TIMESTAMP('30-APR-14','DD-MON-RR HH24.MI.SSXFF'), null, null, TO_TIMESTAMP('15-MAR-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C03' AND tie_breaker = 1);

-- 1960 - Central Assessment period 1
INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C04', 1, TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'C', 1960, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 1240, null, 2500, 0, 4, TO_TIMESTAMP('31-JAN-14','DD-MON-RR HH24.MI.SSXFF'), null, null, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C04' AND tie_breaker = 1);

-- 1960 - Central Assessment period 2
INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C05', 1, TO_TIMESTAMP('01-JAN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-MAR-14','DD-MON-RR HH24.MI.SSXFF'), 'C', 1960, TO_TIMESTAMP('15-MAR-14','DD-MON-RR HH24.MI.SSXFF'), 1240, null, 2450, 0, 4, TO_TIMESTAMP('30-APR-14','DD-MON-RR HH24.MI.SSXFF'), null, null, TO_TIMESTAMP('15-MAR-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C05' AND tie_breaker = 1);

-- 1970 - Officer Assessment period 1
INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C06', 1, TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'C', 1970, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 1240, null, 1000, 0, 4, TO_TIMESTAMP('31-JAN-14','DD-MON-RR HH24.MI.SSXFF'), null, null, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C06' AND tie_breaker = 1);

-- 1970 - Officer Assessment period 2
INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C07', 1, TO_TIMESTAMP('01-JAN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-MAR-14','DD-MON-RR HH24.MI.SSXFF'), 'C', 1970, TO_TIMESTAMP('15-MAR-14','DD-MON-RR HH24.MI.SSXFF'), 1240, null, 1000, 0, 4, TO_TIMESTAMP('30-APR-14','DD-MON-RR HH24.MI.SSXFF'), null, null, TO_TIMESTAMP('15-MAR-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C07' AND tie_breaker = 1);

-- 1980 - Late Filing Penalty (sub_trans=1090) period 1
INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C08', 1, TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'C', 1980, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 1090, null, 100, 0, null, null, null, null, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C08' AND tie_breaker = 1);

-- 1980 - Late Filing Penalty (sub_trans=1090) period 2
INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C09', 1, TO_TIMESTAMP('01-JAN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-MAR-14','DD-MON-RR HH24.MI.SSXFF'), 'C', 1980, TO_TIMESTAMP('15-MAR-14','DD-MON-RR HH24.MI.SSXFF'), 1090, null, 200, 0, null, null, null, null, TO_TIMESTAMP('15-MAR-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C09' AND tie_breaker = 1);

-- 1990 - Late Payment Penalty (sub_trans=1090) period 1
INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C10', 1, TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'C', 1990, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 1090, null, 150, 0, null, null, null, null, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C10' AND tie_breaker = 1);

-- 1990 - Late Payment Penalty (sub_trans=1090) period 2
INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C11', 1, TO_TIMESTAMP('01-JAN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-MAR-14','DD-MON-RR HH24.MI.SSXFF'), 'C', 1990, TO_TIMESTAMP('15-MAR-14','DD-MON-RR HH24.MI.SSXFF'), 1090, null, 200, 0, null, null, null, null, TO_TIMESTAMP('15-MAR-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C11' AND tie_breaker = 1);


-- ============================================================================
-- 3b. MGD_LP_CHARGE - I-type (Interest) rows — one per charge code
--     Used by: getMGDInterestDetails (charge_type_indicator = 'I')
-- ============================================================================

INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001I01', 1, TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'I', 1950, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 1240, 'XW00003001C02', 25.50, 0, null, null, null, null, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001I01' AND tie_breaker = 1);

INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001I02', 1, TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'I', 1960, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 1240, 'XW00003001C04', 35.75, 0, null, null, null, null, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001I02' AND tie_breaker = 1);

INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001I03', 1, TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'I', 1970, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 1240, 'XW00003001C06', 18.25, 0, null, null, null, null, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001I03' AND tie_breaker = 1);

INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001I04', 1, TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'I', 1940, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 1240, 'XW00003001C01', 22.00, 0, null, null, null, null, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001I04' AND tie_breaker = 1);

INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001I05', 1, TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'I', 1980, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 1090, 'XW00003001C08', 12.00, 0, null, null, null, null, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001I05' AND tie_breaker = 1);

INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001I06', 1, TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'I', 1990, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 1090, 'XW00003001C10', 15.00, 0, null, null, null, null, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001I06' AND tie_breaker = 1);


-- ============================================================================
-- 3c. MGD_LP_CHARGE - R-type (Repayment interest) rows — one per charge code
--     Used by: getMGDRepaymentInterestDetails (charge_type_indicator = 'R')
-- ============================================================================

INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001RR3', 1, TO_TIMESTAMP('01-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF'), 'R', 1940, TO_TIMESTAMP('01-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 1090, null, -12.50, 0, null, null, null, null, TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001RR3' AND tie_breaker = 1);

INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001RR4', 1, TO_TIMESTAMP('01-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF'), 'R', 1950, TO_TIMESTAMP('01-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 1090, null, -4.84, 0, null, null, null, null, TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001RR4' AND tie_breaker = 1);

INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001RR8', 1, TO_TIMESTAMP('01-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF'), 'R', 1960, TO_TIMESTAMP('01-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 1090, null, -30.00, 0, null, null, null, null, TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001RR8' AND tie_breaker = 1);

INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001RR5', 1, TO_TIMESTAMP('01-MAR-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-MAY-14','DD-MON-RR HH24.MI.SSXFF'), 'R', 1970, TO_TIMESTAMP('01-MAR-14','DD-MON-RR HH24.MI.SSXFF'), 1090, null, -25.00, 0, null, null, null, null, TO_TIMESTAMP('31-MAY-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001RR5' AND tie_breaker = 1);

INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001RR6', 1, TO_TIMESTAMP('01-JUN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-AUG-14','DD-MON-RR HH24.MI.SSXFF'), 'R', 1980, TO_TIMESTAMP('01-JUN-14','DD-MON-RR HH24.MI.SSXFF'), 1090, null, -50.00, 0, null, null, null, null, TO_TIMESTAMP('31-AUG-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001RR6' AND tie_breaker = 1);

INSERT INTO mgd_lp_charge (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, RELATED_PEN_INT_CHARGE_REF, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001RR7', 1, TO_TIMESTAMP('01-SEP-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('30-NOV-14','DD-MON-RR HH24.MI.SSXFF'), 'R', 1990, TO_TIMESTAMP('01-SEP-14','DD-MON-RR HH24.MI.SSXFF'), 1090, null, -75.00, 0, null, null, null, null, TO_TIMESTAMP('30-NOV-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_charge WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001RR7' AND tie_breaker = 1);


-- ============================================================================
-- 4. MGD_LP_ACCRUING_INTEREST
--    Dates within period window
-- ============================================================================

INSERT INTO mgd_lp_accruing_interest (MGD_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C01', TO_TIMESTAMP('31-JAN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF'), 1, 3000, 28, 3, 6.90, TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_accruing_interest WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C01' AND tie_breaker = 1);

INSERT INTO mgd_lp_accruing_interest (MGD_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C01', TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-MAR-14','DD-MON-RR HH24.MI.SSXFF'), 2, 3000, 31, 3, 7.64, TO_TIMESTAMP('31-MAR-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_accruing_interest WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C01' AND tie_breaker = 2);

INSERT INTO mgd_lp_accruing_interest (MGD_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C02', TO_TIMESTAMP('31-JAN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF'), 1, 4500, 28, 3, 10.36, TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_accruing_interest WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C02' AND tie_breaker = 1);

INSERT INTO mgd_lp_accruing_interest (MGD_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C04', TO_TIMESTAMP('31-JAN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF'), 1, 2500, 28, 3, 5.75, TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_accruing_interest WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C04' AND tie_breaker = 1);

INSERT INTO mgd_lp_accruing_interest (MGD_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C06', TO_TIMESTAMP('31-JAN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF'), 1, 1000, 28, 3, 2.30, TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_accruing_interest WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C06' AND tie_breaker = 1);


-- ============================================================================
-- 5. MGD_LP_LATE_PAY_INTEREST
--    charge_date within period window (>= 01-OCT-2013)
-- ============================================================================

INSERT INTO mgd_lp_late_pay_interest (MGD_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
SELECT 'XWM00003001200', 'XW00003001I01', TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 1, 4500, 30, 3, 5.55, 'XW00003001C02', TO_TIMESTAMP('15-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_late_pay_interest WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001I01' AND tie_breaker = 1);

INSERT INTO mgd_lp_late_pay_interest (MGD_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
SELECT 'XWM00003001200', 'XW00003001I01', TO_TIMESTAMP('15-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-JAN-14','DD-MON-RR HH24.MI.SSXFF'), 2, 4500, 31, 3, 6.30, 'XW00003001C02', TO_TIMESTAMP('15-JAN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_late_pay_interest WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001I01' AND tie_breaker = 2);

INSERT INTO mgd_lp_late_pay_interest (MGD_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
SELECT 'XWM00003001200', 'XW00003001I02', TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 1, 2500, 30, 3, 6.16, 'XW00003001C04', TO_TIMESTAMP('15-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_late_pay_interest WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001I02' AND tie_breaker = 1);

INSERT INTO mgd_lp_late_pay_interest (MGD_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
SELECT 'XWM00003001200', 'XW00003001I03', TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 1, 1000, 30, 3, 2.47, 'XW00003001C06', TO_TIMESTAMP('15-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_late_pay_interest WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001I03' AND tie_breaker = 1);

INSERT INTO mgd_lp_late_pay_interest (MGD_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
SELECT 'XWM00003001200', 'XW00003001I04', TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 1, 3000, 30, 3, 7.40, 'XW00003001C01', TO_TIMESTAMP('15-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_late_pay_interest WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001I04' AND tie_breaker = 1);

INSERT INTO mgd_lp_late_pay_interest (MGD_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
SELECT 'XWM00003001200', 'XW00003001I05', TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 1, 100, 30, 3, 0.25, 'XW00003001C08', TO_TIMESTAMP('15-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_late_pay_interest WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001I05' AND tie_breaker = 1);

INSERT INTO mgd_lp_late_pay_interest (MGD_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
SELECT 'XWM00003001200', 'XW00003001I06', TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 1, 150, 30, 3, 0.37, 'XW00003001C10', TO_TIMESTAMP('15-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_late_pay_interest WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001I06' AND tie_breaker = 1);


-- ============================================================================
-- 6. MGD_LP_PAYMENT
--    payment_post_date within period window
-- ============================================================================

-- Regular payment (type E)
INSERT INTO mgd_lp_payment (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, PAYMENT_POST_DATE, PAYMENT_EDP, PAYMENT_TYPE, PAYMENT_AMOUNT, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C02', 1, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 'E', 1500, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_payment WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C02' AND tie_breaker = 1);

-- Regular payment (type C = cheque)
INSERT INTO mgd_lp_payment (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, PAYMENT_POST_DATE, PAYMENT_EDP, PAYMENT_TYPE, PAYMENT_AMOUNT, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C04', 1, TO_TIMESTAMP('01-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('01-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'C', 1000, TO_TIMESTAMP('01-DEC-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_payment WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C04' AND tie_breaker = 1);

-- Reallocation-in payment (type R) — for getMGDReallocationsInDetails
INSERT INTO mgd_lp_payment (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, PAYMENT_POST_DATE, PAYMENT_EDP, PAYMENT_TYPE, PAYMENT_AMOUNT, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C06', 1, TO_TIMESTAMP('15-JAN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-JAN-14','DD-MON-RR HH24.MI.SSXFF'), 'R', 500, TO_TIMESTAMP('15-JAN-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_payment WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C06' AND tie_breaker = 1);

-- Another regular payment (type E)
INSERT INTO mgd_lp_payment (MGD_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, PAYMENT_POST_DATE, PAYMENT_EDP, PAYMENT_TYPE, PAYMENT_AMOUNT, RECORD_UPDATED)
SELECT 'XWM00003001200', 'XW00003001C01', 1, TO_TIMESTAMP('01-FEB-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('01-FEB-14','DD-MON-RR HH24.MI.SSXFF'), 'E', 500, TO_TIMESTAMP('01-FEB-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_payment WHERE mgd_reg_number = 'XWM00003001200' AND safe_charge_ref = 'XW00003001C01' AND tie_breaker = 1);


-- ============================================================================
-- 7. MGD_LP_PAYMENT_ON_ACCOUNT
-- ============================================================================

INSERT INTO mgd_lp_payment_on_account (MGD_REG_NUMBER, PAYMENT_DOC_NUMBER, TIE_BREAKER, PAYMENT_POST_DATE, PAYMENT_EDP, PAYMENT_TYPE, PAYMENT_AMOUNT, CLEARING_REASON, RECORD_UPDATED)
SELECT 'XWM00003001200', '003001200001', 1, TO_TIMESTAMP('20-NOV-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('20-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 'E', 500, null, TO_TIMESTAMP('20-NOV-13','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_payment_on_account WHERE mgd_reg_number = 'XWM00003001200' AND payment_doc_number = '003001200001' AND tie_breaker = 1);

-- Reallocation-in on account (type R)
INSERT INTO mgd_lp_payment_on_account (MGD_REG_NUMBER, PAYMENT_DOC_NUMBER, TIE_BREAKER, PAYMENT_POST_DATE, PAYMENT_EDP, PAYMENT_TYPE, PAYMENT_AMOUNT, CLEARING_REASON, RECORD_UPDATED)
SELECT 'XWM00003001200', '003001200002', 1, TO_TIMESTAMP('15-FEB-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-FEB-14','DD-MON-RR HH24.MI.SSXFF'), 'R', 250, null, TO_TIMESTAMP('15-FEB-14','DD-MON-RR HH24.MI.SSXFF')
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_payment_on_account WHERE mgd_reg_number = 'XWM00003001200' AND payment_doc_number = '003001200002' AND tie_breaker = 1);


-- ============================================================================
-- 8. MGD_LP_REALLOCATION_OUT
--    reallocation_date within period window
-- ============================================================================

-- Actual repayment (type R, charge_type NULL)
-- PK is (MGD_REG_NUMBER, TIE_BREAKER) only
INSERT INTO mgd_lp_reallocation_out (MGD_REG_NUMBER, TIE_BREAKER, CHARGE_TYPE, REALLOCATION_DATE, REALLOCATION_TYPE, REALLOCATION_AMOUNT, REALLOCATION_EDP, RECORD_UPDATED, CHARGE_REFERENCE)
SELECT 'XWM00003001200', 1, null, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 'R', -100, TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-NOV-13','DD-MON-RR HH24.MI.SSXFF'), 'XW00003001C02'
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_reallocation_out WHERE mgd_reg_number = 'XWM00003001200' AND tie_breaker = 1);

INSERT INTO mgd_lp_reallocation_out (MGD_REG_NUMBER, TIE_BREAKER, CHARGE_TYPE, REALLOCATION_DATE, REALLOCATION_TYPE, REALLOCATION_AMOUNT, REALLOCATION_EDP, RECORD_UPDATED, CHARGE_REFERENCE)
SELECT 'XWM00003001200', 2, null, TO_TIMESTAMP('15-DEC-14','DD-MON-RR HH24.MI.SSXFF'), 'R', -100, TO_TIMESTAMP('15-DEC-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-DEC-14','DD-MON-RR HH24.MI.SSXFF'), 'XW00003001C04'
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_reallocation_out WHERE mgd_reg_number = 'XWM00003001200' AND tie_breaker = 2);

-- Another actual repayment
INSERT INTO mgd_lp_reallocation_out (MGD_REG_NUMBER, TIE_BREAKER, CHARGE_TYPE, REALLOCATION_DATE, REALLOCATION_TYPE, REALLOCATION_AMOUNT, REALLOCATION_EDP, RECORD_UPDATED, CHARGE_REFERENCE)
SELECT 'XWM00003001200', 3, null, TO_TIMESTAMP('15-DEC-14','DD-MON-RR HH24.MI.SSXFF'), 'R', -25, TO_TIMESTAMP('15-DEC-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-DEC-14','DD-MON-RR HH24.MI.SSXFF'), 'XW00003001C02'
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_reallocation_out WHERE mgd_reg_number = 'XWM00003001200' AND tie_breaker = 3);

-- Repayment interest repaid (type R, charge_type 'I')
INSERT INTO mgd_lp_reallocation_out (MGD_REG_NUMBER, TIE_BREAKER, CHARGE_TYPE, REALLOCATION_DATE, REALLOCATION_TYPE, REALLOCATION_AMOUNT, REALLOCATION_EDP, RECORD_UPDATED, CHARGE_REFERENCE)
SELECT 'XWM00003001200', 4, 'I', TO_TIMESTAMP('20-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'R', -25, TO_TIMESTAMP('20-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('20-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'XW00003001C04'
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_reallocation_out WHERE mgd_reg_number = 'XWM00003001200' AND tie_breaker = 4);

-- Reallocation out (type O)
INSERT INTO mgd_lp_reallocation_out (MGD_REG_NUMBER, TIE_BREAKER, CHARGE_TYPE, REALLOCATION_DATE, REALLOCATION_TYPE, REALLOCATION_AMOUNT, REALLOCATION_EDP, RECORD_UPDATED, CHARGE_REFERENCE)
SELECT 'XWM00003001200', 5, null, TO_TIMESTAMP('10-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'O', -150, TO_TIMESTAMP('10-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('10-DEC-13','DD-MON-RR HH24.MI.SSXFF'), 'XW00003001C02'
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_reallocation_out WHERE mgd_reg_number = 'XWM00003001200' AND tie_breaker = 5);

INSERT INTO mgd_lp_reallocation_out (MGD_REG_NUMBER, TIE_BREAKER, CHARGE_TYPE, REALLOCATION_DATE, REALLOCATION_TYPE, REALLOCATION_AMOUNT, REALLOCATION_EDP, RECORD_UPDATED, CHARGE_REFERENCE)
SELECT 'XWM00003001200', 6, null, TO_TIMESTAMP('20-JAN-14','DD-MON-RR HH24.MI.SSXFF'), 'O', -150, TO_TIMESTAMP('20-JAN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('20-JAN-14','DD-MON-RR HH24.MI.SSXFF'), 'XW00003001C04'
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_lp_reallocation_out WHERE mgd_reg_number = 'XWM00003001200' AND tie_breaker = 6);


-- ============================================================================
-- 9. MGD_RETURN_DETAILS
--    due_date before period_end so outstanding returns show up
-- ============================================================================

INSERT INTO mgd_return_details (MGD_REG_NUMBER, CONSEC_NO, FORM_BUNDLE_ID, PERIOD_START_DATE, PERIOD_END_DATE, DUE_DATE, SUBMITTED_DATE, ACK_REF, ICR_STATUS, RECORD_UPDATED, REMINDER_EMAIL_SENT)
SELECT 'XWM00003001200', 1, null, TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-DEC-13','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('30-NOV-13','DD-MON-RR HH24.MI.SSXFF'), null, null, 'CREATED', TO_TIMESTAMP('01-OCT-13','DD-MON-RR HH24.MI.SSXFF'), null
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_return_details WHERE mgd_reg_number = 'XWM00003001200' AND consec_no = 1);

INSERT INTO mgd_return_details (MGD_REG_NUMBER, CONSEC_NO, FORM_BUNDLE_ID, PERIOD_START_DATE, PERIOD_END_DATE, DUE_DATE, SUBMITTED_DATE, ACK_REF, ICR_STATUS, RECORD_UPDATED, REMINDER_EMAIL_SENT)
SELECT 'XWM00003001200', 2, null, TO_TIMESTAMP('01-JAN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-MAR-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('28-FEB-14','DD-MON-RR HH24.MI.SSXFF'), null, null, 'CREATED', TO_TIMESTAMP('01-JAN-14','DD-MON-RR HH24.MI.SSXFF'), null
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_return_details WHERE mgd_reg_number = 'XWM00003001200' AND consec_no = 2);

INSERT INTO mgd_return_details (MGD_REG_NUMBER, CONSEC_NO, FORM_BUNDLE_ID, PERIOD_START_DATE, PERIOD_END_DATE, DUE_DATE, SUBMITTED_DATE, ACK_REF, ICR_STATUS, RECORD_UPDATED, REMINDER_EMAIL_SENT)
SELECT 'XWM00003001200', 3, 1001, TO_TIMESTAMP('01-APR-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('30-JUN-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('31-JUL-14','DD-MON-RR HH24.MI.SSXFF'), TO_TIMESTAMP('15-JUL-14','DD-MON-RR HH24.MI.SSXFF'), 'ACK001', 'RECEIVED', TO_TIMESTAMP('15-JUL-14','DD-MON-RR HH24.MI.SSXFF'), null
FROM dual WHERE NOT EXISTS (SELECT 1 FROM mgd_return_details WHERE mgd_reg_number = 'XWM00003001200' AND consec_no = 3);


COMMIT;

-- ============================================================================
-- SPROC COVERAGE SUMMARY
-- ============================================================================
-- 1.  getMGDPeriods                  - paye_data.safe_lp_sequence (pre-existing)
-- 2.  getMGDAccountOverview          - MGD_LP_TOTAL + MGD_OPERATOR_DETAILS
-- 3.  getMGDAccruingDrilldown        - MGD_LP_CHARGE(C) + MGD_LP_ACCRUING_INTEREST
-- 4.  getMGDActualRepayments         - MGD_LP_TOTAL + MGD_LP_REALLOCATION_OUT(R,null)
-- 5.  getMGDAssessmentsWithoutReturn - MGD_LP_TOTAL + MGD_LP_CHARGE(C,1960)
-- 6.  getMGDCurrentPosition          - MGD_LP_TOTAL + MGD_RETURN_DETAILS
-- 7.  getMGDInterestAccruingDetails  - MGD_LP_CHARGE(C,interest-bearing)
-- 8.  getMGDInterestDetails          - MGD_LP_TOTAL + MGD_LP_CHARGE(I)
-- 9.  getMGDInterestDrilldown        - MGD_LP_LATE_PAY_INTEREST + MGD_LP_CHARGE
-- 10. getMGDInterestOverview         - MGD_LP_TOTAL + getAccruingIntTotal
-- 11. getMGDOperatorDetails          - MGD_OPERATOR_DETAILS
-- 12. getMGDPayments                 - MGD_LP_PAYMENT + MGD_LP_PAYMENT_ON_ACCOUNT
-- 13. getMGDPenalties                - MGD_LP_TOTAL + MGD_LP_CHARGE(C,1980/1990,sub=1090)
-- 14. getMGDReallocationsDetails     - MGD_LP_TOTAL
-- 15. getMGDReallocationsInDetails   - MGD_LP_PAYMENT(R) + MGD_LP_PAYMENT_ON_ACCOUNT(R)
-- 16. getMGDReallocationsOutDetails  - MGD_LP_REALLOCATION_OUT(O)
-- 17. getMGDRepaymentSummary         - MGD_LP_TOTAL
-- 18. getMGDRepaymentDrilldown       - STUB (returns 0 by design)
-- 19. getMGDRepaymentInterestDetails - MGD_LP_CHARGE(R) - all 6 codes
-- 20. getMGDRepaymentInterestRepaid  - MGD_LP_REALLOCATION_OUT(R,I)
-- 21. getMGDReturnsSubmitted         - MGD_LP_CHARGE(C,1950)
-- 22. getOtherAssessmentDetails      - MGD_LP_CHARGE(C,1970)
-- 23. version (x2)                   - No data needed
-- 24. getAccruingIntTotal            - Calls getMGDInterestAccruingDetails
-- ============================================================================
