-- ============================================================================
-- Grand Test Script for GTR_LNP_PK Package
-- Registration: XBA00003000001
--
-- Inserts test data into ALL tables so that every stored procedure in
-- GTR_LNP_PK returns data with all applicable charge codes.
--
-- Updates safe_lp_sequence so the period window covers 2025-2026 dates.
-- All test dates are set within that window.
--
-- Tables populated:
--   1. GTR_OPERATOR_DETAILS     (getGTROperatorDetails)
--   2. GTR_LP_TOTAL             (14 sprocs use totals)
--   3. GTR_LP_CHARGE            (C-type, I-type, R-type for all 9 codes)
--   4. GTR_LP_ACCRUING_INTEREST (getGTRAccruingDrilldown, getGTRInterestAccruingDetails)
--   5. GTR_LP_LATE_PAY_INTEREST (getGTRInterestDetails, getGTRInterestDrilldown)
--   6. GTR_LP_PAYMENT           (getGTRPayments, getGTRReallocationsInDetails)
--   7. GTR_LP_PAYMENT_ON_ACCOUNT (getGTRPayments, getGTRReallocationsInDetails)
--   8. GTR_LP_REALLOCATION_OUT  (getGTRActualRepayments, getGTRReallocationsOutDetails,
--                                 getGTRRepaymentInterestRepaid)
--
-- All 9 GTR charge codes covered (SAFE_MTRANS_CODE):
--   2640 - PPLR interest bearing
--   2650 - Return Charge
--   2655 - Return Interest
--   2660 - Central Assessment
--   2670 - Officer Assessment
--   2680 - Late Filing Penalty
--   2685 - Late Filing Penalty interest
--   2690 - Late Payment Penalty
--   2695 - Late Payment Penalty interest
--
-- Safe to run multiple times — deletes all existing data first.
-- ============================================================================

SET DEFINE OFF;

-- ============================================================================
-- 0. UPDATE PERIOD WINDOW
--    Update safe_lp_sequence so period covers 2025-2026 dates.
--    New period: 01-APR-2025 to 18-JUN-2026
-- ============================================================================
UPDATE safe_lp_sequence SET processed_date = TO_DATE('18-JUN-26','DD-MON-RR');
COMMIT;

-- ============================================================================
-- 0b. CLEAN SLATE — Delete all existing data for XBA00003000001
-- ============================================================================
DELETE FROM gtr_lp_accruing_interest WHERE gtr_reg_number = 'XBA00003000001';
DELETE FROM gtr_lp_late_pay_interest WHERE gtr_reg_number = 'XBA00003000001';
DELETE FROM gtr_lp_payment WHERE gtr_reg_number = 'XBA00003000001';
DELETE FROM gtr_lp_payment_on_account WHERE gtr_reg_number = 'XBA00003000001';
DELETE FROM gtr_lp_reallocation_out WHERE gtr_reg_number = 'XBA00003000001';
DELETE FROM gtr_lp_charge WHERE gtr_reg_number = 'XBA00003000001';
DELETE FROM gtr_lp_total WHERE gtr_reg_number = 'XBA00003000001';
DELETE FROM gtr_operator_details WHERE gtr_reg_number = 'XBA00003000001';
COMMIT;


-- ============================================================================
-- 1. GTR_OPERATOR_DETAILS
--    PK: (GTR_REG_NUMBER, BUSINESS_PARTNER_NUMBER)
-- ============================================================================
INSERT INTO gtr_operator_details (
    GTR_REG_NUMBER, BUSINESS_PARTNER_NUMBER, GTR_REGISTRATION_TYPE,
    SOLE_PROP_TITLE, SOLE_PROP_FIRST_NAME, SOLE_PROP_LAST_NAME,
    REP_MEMBER_OF_GROUP, BUSINESS_NAME, TYPE_OF_BUSINESS,
    BUS_ADDRESS_1, BUS_ADDRESS_2, BUS_ADDRESS_3, BUS_ADDRESS_4,
    BUS_POSTCODE, BUS_COUNTRY, BUS_IOM_OR_CI,
    BUS_PHONE_NUMBER, BUS_MOBILE_PHONE_NUMBER, BUS_EMAIL_ADDR,
    TRADING_NAME, VRN, NINO, UTR, DATE_OF_BIRTH,
    REGISTRATION_DATE, DATE_OF_DEREGISTRATION, REASON_OF_DEREGISTRATION,
    CORRES_NAME, CORRES_ADDRESS_1, CORRES_ADDRESS_2, CORRES_ADDRESS_3, CORRES_ADDRESS_4,
    CORRES_POSTCODE, CORRES_COUNTRY, CORRES_PHONE_NUMBER, CORRES_MOBILE_PHONE_NUMBER,
    CORRES_EMAIL_ADDR, RETURN_PERIOD_ID, RECORD_UPDATED
)
VALUES (
    'XBA00003000001', '0100099901', 'GBD',
    'Mr', 'Test', 'Operator',
    'N', 'GTR Test Business Ltd', 'Corporate Body',
    '1 GTR Test Street', 'Test Town', 'Test County', null,
    'GT1 1ST', null, 'N',
    '01234 567890', '07979 123456', 'gtr-test@test.com',
    'GTR Test Trading', null, null, null, TO_DATE('01-JAN-80','DD-MON-RR'),
    TO_DATE('01-JAN-25','DD-MON-RR'), null, null,
    'Corres Name', 'Corres Addr 1', 'Corres Addr 2', 'Corres Addr 3', null,
    'CO1 1RR', null, '01234 111111', '07979 222222',
    'corres@test.com', 1, TO_DATE('01-JAN-25','DD-MON-RR')
);


-- ============================================================================
-- 2. GTR_LP_TOTAL
-- ============================================================================
INSERT INTO gtr_lp_total (
    GTR_REG_NUMBER, BALANCE_BROUGHT_FORWARD, RETURN_CHARGE_AMOUNT,
    CENTRAL_ASSESSMENT_AMOUNT, SUBTOTAL_RETURNS, TOTAL_PENALTY_AMOUNT,
    TOTAL_ADJUSTMENT_AMOUNT, TOTAL_REALLOCATION_IN, TOTAL_REALLOCATION_OUT,
    TOTAL_REALLOCATION, OFFICER_ASSESSMENT_AMOUNT, TOTAL_LATE_PAY_INTEREST,
    TOTAL_REPAY_INTEREST, TOTAL_INTEREST, SUBTOTAL_OTHERS,
    TOTAL_ALLOCATED_PAYMENTS, TOTAL_PAY_ON_ACCOUNT, TOTAL_PAYMENTS,
    TOTAL_ACTUAL_REPAYMENTS, TOTAL_RRI, TOTAL_REPAYMENTS,
    SUBTOTAL_PAYMENTS, TOTAL_AMOUNT_DUE, RECORD_UPDATED
)
VALUES (
    'XBA00003000001',
    5000,       -- BALANCE_BROUGHT_FORWARD
    8500,       -- RETURN_CHARGE_AMOUNT (2650)
    4950,       -- CENTRAL_ASSESSMENT_AMOUNT (2660)
    13450,      -- SUBTOTAL_RETURNS
    650,        -- TOTAL_PENALTY_AMOUNT (2680+2690)
    100,        -- TOTAL_ADJUSTMENT_AMOUNT
    500,        -- TOTAL_REALLOCATION_IN
    -300,       -- TOTAL_REALLOCATION_OUT
    200,        -- TOTAL_REALLOCATION
    2000,       -- OFFICER_ASSESSMENT_AMOUNT (2670)
    150,        -- TOTAL_LATE_PAY_INTEREST
    75,         -- TOTAL_REPAY_INTEREST
    225,        -- TOTAL_INTEREST
    2875,       -- SUBTOTAL_OTHERS
    3000,       -- TOTAL_ALLOCATED_PAYMENTS
    500,        -- TOTAL_PAY_ON_ACCOUNT
    3500,       -- TOTAL_PAYMENTS
    -200,       -- TOTAL_ACTUAL_REPAYMENTS
    -50,        -- TOTAL_RRI
    -250,       -- TOTAL_REPAYMENTS
    4000,       -- SUBTOTAL_PAYMENTS
    18000,      -- TOTAL_AMOUNT_DUE
    TO_DATE('01-JUN-25','DD-MON-RR')
);


-- ============================================================================
-- 3a. GTR_LP_CHARGE - C-type (Charge) rows for all 9 charge codes
--     PK: (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER)
--     Dates within period window (01-APR-2025 onwards)
--
--     Sproc filters:
--       getGTRReturnsSubmitted:         safe_mtrans_code = 2650
--       getGTRAssessmentsWithoutReturn: safe_mtrans_code = 2660
--       getOtherAssessmentDetails:      safe_mtrans_code = 2670
--       getGTRPenalties:               safe_mtrans_code IN (2680,2690) AND safe_sub_trans_code = 1090
--       getGTRInterestAccruingDetails:  charge_type_indicator = 'C' AND interest-bearing
-- ============================================================================

-- 2640 - PPLR interest bearing (interest-bearing for accruing interest)
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C01', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'C', 2640, TO_DATE('15-JUN-25','DD-MON-RR'), 1400, 3000, 0, 4, TO_DATE('31-AUG-25','DD-MON-RR'), null, null, TO_DATE('15-JUN-25','DD-MON-RR'));

-- 2650 - Return Charge period 1 (interest-bearing)
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C02', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'C', 2650, TO_DATE('15-JUN-25','DD-MON-RR'), 1400, 4500, 0, 4, TO_DATE('31-AUG-25','DD-MON-RR'), null, null, TO_DATE('15-JUN-25','DD-MON-RR'));

-- 2650 - Return Charge period 2
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C03', 1, TO_DATE('01-AUG-25','DD-MON-RR'), TO_DATE('31-OCT-25','DD-MON-RR'), 'C', 2650, TO_DATE('15-SEP-25','DD-MON-RR'), 1400, 4000, 0, 4, TO_DATE('30-NOV-25','DD-MON-RR'), null, null, TO_DATE('15-SEP-25','DD-MON-RR'));

-- 2655 - Return Interest (interest-bearing)
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C04', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'C', 2655, TO_DATE('15-JUN-25','DD-MON-RR'), 1400, 1500, 0, 4, TO_DATE('31-AUG-25','DD-MON-RR'), null, null, TO_DATE('15-JUN-25','DD-MON-RR'));

-- 2660 - Central Assessment period 1 (interest-bearing)
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C05', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'C', 2660, TO_DATE('15-JUN-25','DD-MON-RR'), 1400, 2500, 0, 4, TO_DATE('31-AUG-25','DD-MON-RR'), null, null, TO_DATE('15-JUN-25','DD-MON-RR'));

-- 2660 - Central Assessment period 2
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C06', 1, TO_DATE('01-AUG-25','DD-MON-RR'), TO_DATE('31-OCT-25','DD-MON-RR'), 'C', 2660, TO_DATE('15-SEP-25','DD-MON-RR'), 1400, 2450, 0, 4, TO_DATE('30-NOV-25','DD-MON-RR'), null, null, TO_DATE('15-SEP-25','DD-MON-RR'));

-- 2670 - Officer Assessment period 1 (interest-bearing)
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C07', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'C', 2670, TO_DATE('15-JUN-25','DD-MON-RR'), 1400, 1000, 0, 4, TO_DATE('31-AUG-25','DD-MON-RR'), null, null, TO_DATE('15-JUN-25','DD-MON-RR'));

-- 2670 - Officer Assessment period 2
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C08', 1, TO_DATE('01-AUG-25','DD-MON-RR'), TO_DATE('31-OCT-25','DD-MON-RR'), 'C', 2670, TO_DATE('15-SEP-25','DD-MON-RR'), 1400, 1000, 0, 4, TO_DATE('30-NOV-25','DD-MON-RR'), null, null, TO_DATE('15-SEP-25','DD-MON-RR'));

-- 2680 - Late Filing Penalty (sub_trans=1090) period 1
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C09', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'C', 2680, TO_DATE('15-JUN-25','DD-MON-RR'), 1090, 100, 0, null, null, null, null, TO_DATE('15-JUN-25','DD-MON-RR'));

-- 2680 - Late Filing Penalty (sub_trans=1090) period 2
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C10', 1, TO_DATE('01-AUG-25','DD-MON-RR'), TO_DATE('31-OCT-25','DD-MON-RR'), 'C', 2680, TO_DATE('15-SEP-25','DD-MON-RR'), 1090, 200, 0, null, null, null, null, TO_DATE('15-SEP-25','DD-MON-RR'));

-- 2685 - Late Filing Penalty interest
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C11', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'C', 2685, TO_DATE('15-JUN-25','DD-MON-RR'), 1090, 50, 0, 4, TO_DATE('31-AUG-25','DD-MON-RR'), null, null, TO_DATE('15-JUN-25','DD-MON-RR'));

-- 2690 - Late Payment Penalty (sub_trans=1090) period 1
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C12', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'C', 2690, TO_DATE('15-JUN-25','DD-MON-RR'), 1090, 150, 0, null, null, null, null, TO_DATE('15-JUN-25','DD-MON-RR'));

-- 2690 - Late Payment Penalty (sub_trans=1090) period 2
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C13', 1, TO_DATE('01-AUG-25','DD-MON-RR'), TO_DATE('31-OCT-25','DD-MON-RR'), 'C', 2690, TO_DATE('15-SEP-25','DD-MON-RR'), 1090, 200, 0, null, null, null, null, TO_DATE('15-SEP-25','DD-MON-RR'));

-- 2695 - Late Payment Penalty interest
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C14', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'C', 2695, TO_DATE('15-JUN-25','DD-MON-RR'), 1090, 75, 0, 4, TO_DATE('31-AUG-25','DD-MON-RR'), null, null, TO_DATE('15-JUN-25','DD-MON-RR'));


-- ============================================================================
-- 3b. GTR_LP_CHARGE - I-type (Interest) rows — one per charge code (all 9)
--     Used by: getGTRInterestDetails (charge_type_indicator = 'I')
-- ============================================================================

-- 2640 - PPLR interest bearing
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000I01', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'I', 2640, TO_DATE('15-AUG-25','DD-MON-RR'), 1400, 22.00, 0, null, null, null, null, TO_DATE('15-AUG-25','DD-MON-RR'));

-- 2650 - Return Charge
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000I02', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'I', 2650, TO_DATE('15-AUG-25','DD-MON-RR'), 1400, 25.50, 0, null, null, null, null, TO_DATE('15-AUG-25','DD-MON-RR'));

-- 2655 - Return Interest
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000I03', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'I', 2655, TO_DATE('15-AUG-25','DD-MON-RR'), 1400, 10.50, 0, null, null, null, null, TO_DATE('15-AUG-25','DD-MON-RR'));

-- 2660 - Central Assessment
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000I04', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'I', 2660, TO_DATE('15-AUG-25','DD-MON-RR'), 1400, 35.75, 0, null, null, null, null, TO_DATE('15-AUG-25','DD-MON-RR'));

-- 2670 - Officer Assessment
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000I05', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'I', 2670, TO_DATE('15-AUG-25','DD-MON-RR'), 1400, 18.25, 0, null, null, null, null, TO_DATE('15-AUG-25','DD-MON-RR'));

-- 2680 - Late Filing Penalty
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000I06', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'I', 2680, TO_DATE('15-AUG-25','DD-MON-RR'), 1090, 12.00, 0, null, null, null, null, TO_DATE('15-AUG-25','DD-MON-RR'));

-- 2685 - Late Filing Penalty interest
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000I07', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'I', 2685, TO_DATE('15-AUG-25','DD-MON-RR'), 1090, 8.50, 0, null, null, null, null, TO_DATE('15-AUG-25','DD-MON-RR'));

-- 2690 - Late Payment Penalty
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000I08', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'I', 2690, TO_DATE('15-AUG-25','DD-MON-RR'), 1090, 15.00, 0, null, null, null, null, TO_DATE('15-AUG-25','DD-MON-RR'));

-- 2695 - Late Payment Penalty interest
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000I09', 1, TO_DATE('01-MAY-25','DD-MON-RR'), TO_DATE('31-JUL-25','DD-MON-RR'), 'I', 2695, TO_DATE('15-AUG-25','DD-MON-RR'), 1090, 9.75, 0, null, null, null, null, TO_DATE('15-AUG-25','DD-MON-RR'));


-- ============================================================================
-- 3c. GTR_LP_CHARGE - R-type (Repayment interest) rows — one per charge code (all 9)
--     Used by: getGTRRepaymentInterestDetails (charge_type_indicator = 'R')
-- ============================================================================

-- 2640 - PPLR interest bearing
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000R01', 1, TO_DATE('01-AUG-25','DD-MON-RR'), TO_DATE('31-OCT-25','DD-MON-RR'), 'R', 2640, TO_DATE('15-NOV-25','DD-MON-RR'), 1090, -12.50, 0, null, null, null, null, TO_DATE('15-NOV-25','DD-MON-RR'));

-- 2650 - Return Charge
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000R02', 1, TO_DATE('01-AUG-25','DD-MON-RR'), TO_DATE('31-OCT-25','DD-MON-RR'), 'R', 2650, TO_DATE('15-NOV-25','DD-MON-RR'), 1090, -4.84, 0, null, null, null, null, TO_DATE('15-NOV-25','DD-MON-RR'));

-- 2655 - Return Interest
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000R03', 1, TO_DATE('01-AUG-25','DD-MON-RR'), TO_DATE('31-OCT-25','DD-MON-RR'), 'R', 2655, TO_DATE('15-NOV-25','DD-MON-RR'), 1090, -8.50, 0, null, null, null, null, TO_DATE('15-NOV-25','DD-MON-RR'));

-- 2660 - Central Assessment
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000R04', 1, TO_DATE('01-NOV-25','DD-MON-RR'), TO_DATE('31-JAN-26','DD-MON-RR'), 'R', 2660, TO_DATE('15-FEB-26','DD-MON-RR'), 1090, -30.00, 0, null, null, null, null, TO_DATE('15-FEB-26','DD-MON-RR'));

-- 2670 - Officer Assessment
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000R05', 1, TO_DATE('01-NOV-25','DD-MON-RR'), TO_DATE('31-JAN-26','DD-MON-RR'), 'R', 2670, TO_DATE('15-FEB-26','DD-MON-RR'), 1090, -25.00, 0, null, null, null, null, TO_DATE('15-FEB-26','DD-MON-RR'));

-- 2680 - Late Filing Penalty
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000R06', 1, TO_DATE('01-FEB-26','DD-MON-RR'), TO_DATE('30-APR-26','DD-MON-RR'), 'R', 2680, TO_DATE('15-MAR-26','DD-MON-RR'), 1090, -50.00, 0, null, null, null, null, TO_DATE('15-MAR-26','DD-MON-RR'));

-- 2685 - Late Filing Penalty interest
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000R07', 1, TO_DATE('01-FEB-26','DD-MON-RR'), TO_DATE('30-APR-26','DD-MON-RR'), 'R', 2685, TO_DATE('15-MAR-26','DD-MON-RR'), 1090, -15.00, 0, null, null, null, null, TO_DATE('15-MAR-26','DD-MON-RR'));

-- 2690 - Late Payment Penalty
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000R08', 1, TO_DATE('01-MAR-26','DD-MON-RR'), TO_DATE('31-MAY-26','DD-MON-RR'), 'R', 2690, TO_DATE('15-APR-26','DD-MON-RR'), 1090, -75.00, 0, null, null, null, null, TO_DATE('15-APR-26','DD-MON-RR'));

-- 2695 - Late Payment Penalty interest
INSERT INTO gtr_lp_charge (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, CHARGE_PERIOD_START_DATE, CHARGE_PERIOD_END_DATE, CHARGE_TYPE_INDICATOR, SAFE_MTRANS_CODE, CHARGE_DATE, SAFE_SUB_TRANS_CODE, CHARGE_AMOUNT, ADJUSTMENT_AMOUNT, INTEREST_FLAG, INTEREST_START_DATE, CLEARING_REASON, CLEARING_VALUE_DATE, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000R09', 1, TO_DATE('01-MAR-26','DD-MON-RR'), TO_DATE('31-MAY-26','DD-MON-RR'), 'R', 2695, TO_DATE('15-APR-26','DD-MON-RR'), 1090, -20.00, 0, null, null, null, null, TO_DATE('15-APR-26','DD-MON-RR'));


-- ============================================================================
-- 4. GTR_LP_ACCRUING_INTEREST
--    PK: (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER)
-- ============================================================================

INSERT INTO gtr_lp_accruing_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C01', TO_DATE('31-AUG-25','DD-MON-RR'), TO_DATE('30-SEP-25','DD-MON-RR'), 1, 3000, 30, 3, 7.40, TO_DATE('30-SEP-25','DD-MON-RR'));
INSERT INTO gtr_lp_accruing_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C01', TO_DATE('30-SEP-25','DD-MON-RR'), TO_DATE('31-OCT-25','DD-MON-RR'), 2, 3000, 31, 3, 7.64, TO_DATE('31-OCT-25','DD-MON-RR'));
INSERT INTO gtr_lp_accruing_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C02', TO_DATE('31-AUG-25','DD-MON-RR'), TO_DATE('30-SEP-25','DD-MON-RR'), 1, 4500, 30, 3, 11.10, TO_DATE('30-SEP-25','DD-MON-RR'));
INSERT INTO gtr_lp_accruing_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C04', TO_DATE('31-AUG-25','DD-MON-RR'), TO_DATE('30-SEP-25','DD-MON-RR'), 1, 1500, 30, 3, 3.70, TO_DATE('30-SEP-25','DD-MON-RR'));
INSERT INTO gtr_lp_accruing_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C05', TO_DATE('31-AUG-25','DD-MON-RR'), TO_DATE('30-SEP-25','DD-MON-RR'), 1, 2500, 30, 3, 6.16, TO_DATE('30-SEP-25','DD-MON-RR'));
INSERT INTO gtr_lp_accruing_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C07', TO_DATE('31-AUG-25','DD-MON-RR'), TO_DATE('30-SEP-25','DD-MON-RR'), 1, 1000, 30, 3, 2.47, TO_DATE('30-SEP-25','DD-MON-RR'));
INSERT INTO gtr_lp_accruing_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C11', TO_DATE('31-AUG-25','DD-MON-RR'), TO_DATE('30-SEP-25','DD-MON-RR'), 1, 50, 30, 3, 0.12, TO_DATE('30-SEP-25','DD-MON-RR'));
INSERT INTO gtr_lp_accruing_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C14', TO_DATE('31-AUG-25','DD-MON-RR'), TO_DATE('30-SEP-25','DD-MON-RR'), 1, 75, 30, 3, 0.19, TO_DATE('30-SEP-25','DD-MON-RR'));


-- ============================================================================
-- 5. GTR_LP_LATE_PAY_INTEREST
--    PK: (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, CHARGE_DATE)
--    One LPI row per I-type charge (all 9 codes)
-- ============================================================================

INSERT INTO gtr_lp_late_pay_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
VALUES ('XBA00003000001', 'XB00003000I01', TO_DATE('15-AUG-25','DD-MON-RR'), TO_DATE('15-SEP-25','DD-MON-RR'), 1, 3000, 31, 3, 7.64, 'XB00003000C01', TO_DATE('15-SEP-25','DD-MON-RR'), TO_DATE('15-AUG-25','DD-MON-RR'));

INSERT INTO gtr_lp_late_pay_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
VALUES ('XBA00003000001', 'XB00003000I01', TO_DATE('15-SEP-25','DD-MON-RR'), TO_DATE('15-OCT-25','DD-MON-RR'), 2, 3000, 30, 3, 7.40, 'XB00003000C01', TO_DATE('15-OCT-25','DD-MON-RR'), TO_DATE('15-AUG-25','DD-MON-RR'));

INSERT INTO gtr_lp_late_pay_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
VALUES ('XBA00003000001', 'XB00003000I02', TO_DATE('15-AUG-25','DD-MON-RR'), TO_DATE('15-SEP-25','DD-MON-RR'), 1, 4500, 31, 3, 11.47, 'XB00003000C02', TO_DATE('15-SEP-25','DD-MON-RR'), TO_DATE('15-AUG-25','DD-MON-RR'));

INSERT INTO gtr_lp_late_pay_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
VALUES ('XBA00003000001', 'XB00003000I03', TO_DATE('15-AUG-25','DD-MON-RR'), TO_DATE('15-SEP-25','DD-MON-RR'), 1, 1500, 31, 3, 3.82, 'XB00003000C04', TO_DATE('15-SEP-25','DD-MON-RR'), TO_DATE('15-AUG-25','DD-MON-RR'));

INSERT INTO gtr_lp_late_pay_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
VALUES ('XBA00003000001', 'XB00003000I04', TO_DATE('15-AUG-25','DD-MON-RR'), TO_DATE('15-SEP-25','DD-MON-RR'), 1, 2500, 31, 3, 6.37, 'XB00003000C05', TO_DATE('15-SEP-25','DD-MON-RR'), TO_DATE('15-AUG-25','DD-MON-RR'));

INSERT INTO gtr_lp_late_pay_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
VALUES ('XBA00003000001', 'XB00003000I05', TO_DATE('15-AUG-25','DD-MON-RR'), TO_DATE('15-SEP-25','DD-MON-RR'), 1, 1000, 31, 3, 2.55, 'XB00003000C07', TO_DATE('15-SEP-25','DD-MON-RR'), TO_DATE('15-AUG-25','DD-MON-RR'));

INSERT INTO gtr_lp_late_pay_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
VALUES ('XBA00003000001', 'XB00003000I06', TO_DATE('15-AUG-25','DD-MON-RR'), TO_DATE('15-SEP-25','DD-MON-RR'), 1, 100, 31, 3, 0.26, 'XB00003000C09', TO_DATE('15-SEP-25','DD-MON-RR'), TO_DATE('15-AUG-25','DD-MON-RR'));

INSERT INTO gtr_lp_late_pay_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
VALUES ('XBA00003000001', 'XB00003000I07', TO_DATE('15-AUG-25','DD-MON-RR'), TO_DATE('15-SEP-25','DD-MON-RR'), 1, 50, 31, 3, 0.13, 'XB00003000C11', TO_DATE('15-SEP-25','DD-MON-RR'), TO_DATE('15-AUG-25','DD-MON-RR'));

INSERT INTO gtr_lp_late_pay_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
VALUES ('XBA00003000001', 'XB00003000I08', TO_DATE('15-AUG-25','DD-MON-RR'), TO_DATE('15-SEP-25','DD-MON-RR'), 1, 150, 31, 3, 0.38, 'XB00003000C12', TO_DATE('15-SEP-25','DD-MON-RR'), TO_DATE('15-AUG-25','DD-MON-RR'));

INSERT INTO gtr_lp_late_pay_interest (GTR_REG_NUMBER, SAFE_CHARGE_REF, CALCULATION_FROM_DATE, CALCULATION_TO_DATE, TIE_BREAKER, AMOUNT_OUTSTANDING, NO_OF_DAYS, INTEREST_RATE, INTEREST_AMOUNT, ORIGINATING_CHARGE_REF, RECORD_UPDATED, CHARGE_DATE)
VALUES ('XBA00003000001', 'XB00003000I09', TO_DATE('15-AUG-25','DD-MON-RR'), TO_DATE('15-SEP-25','DD-MON-RR'), 1, 75, 31, 3, 0.19, 'XB00003000C14', TO_DATE('15-SEP-25','DD-MON-RR'), TO_DATE('15-AUG-25','DD-MON-RR'));


-- ============================================================================
-- 6. GTR_LP_PAYMENT
--    PK: (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER)
-- ============================================================================

-- Regular payments (type E, C)
INSERT INTO gtr_lp_payment (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, PAYMENT_POST_DATE, PAYMENT_EDP, PAYMENT_TYPE, PAYMENT_AMOUNT, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C02', 1, TO_DATE('01-JUL-25','DD-MON-RR'), TO_DATE('01-JUL-25','DD-MON-RR'), 'E', 1500, TO_DATE('01-JUL-25','DD-MON-RR'));

INSERT INTO gtr_lp_payment (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, PAYMENT_POST_DATE, PAYMENT_EDP, PAYMENT_TYPE, PAYMENT_AMOUNT, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C05', 1, TO_DATE('15-AUG-25','DD-MON-RR'), TO_DATE('15-AUG-25','DD-MON-RR'), 'C', 1000, TO_DATE('15-AUG-25','DD-MON-RR'));

-- Reallocation-in payment (type R)
INSERT INTO gtr_lp_payment (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, PAYMENT_POST_DATE, PAYMENT_EDP, PAYMENT_TYPE, PAYMENT_AMOUNT, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C07', 1, TO_DATE('01-OCT-25','DD-MON-RR'), TO_DATE('01-OCT-25','DD-MON-RR'), 'R', 500, TO_DATE('01-OCT-25','DD-MON-RR'));

-- Another regular payment
INSERT INTO gtr_lp_payment (GTR_REG_NUMBER, SAFE_CHARGE_REF, TIE_BREAKER, PAYMENT_POST_DATE, PAYMENT_EDP, PAYMENT_TYPE, PAYMENT_AMOUNT, RECORD_UPDATED)
VALUES ('XBA00003000001', 'XB00003000C03', 1, TO_DATE('15-NOV-25','DD-MON-RR'), TO_DATE('15-NOV-25','DD-MON-RR'), 'E', 500, TO_DATE('15-NOV-25','DD-MON-RR'));


-- ============================================================================
-- 7. GTR_LP_PAYMENT_ON_ACCOUNT
--    PK: (GTR_REG_NUMBER, PAYMENT_DOC_NUMBER, TIE_BREAKER)
-- ============================================================================

INSERT INTO gtr_lp_payment_on_account (GTR_REG_NUMBER, PAYMENT_DOC_NUMBER, TIE_BREAKER, PAYMENT_POST_DATE, PAYMENT_EDP, PAYMENT_TYPE, PAYMENT_AMOUNT, CLEARING_REASON, RECORD_UPDATED)
VALUES ('XBA00003000001', '000300000101', 1, TO_DATE('20-JUL-25','DD-MON-RR'), TO_DATE('20-JUL-25','DD-MON-RR'), 'E', 500, null, TO_DATE('20-JUL-25','DD-MON-RR'));

-- Reallocation-in on account (type R)
INSERT INTO gtr_lp_payment_on_account (GTR_REG_NUMBER, PAYMENT_DOC_NUMBER, TIE_BREAKER, PAYMENT_POST_DATE, PAYMENT_EDP, PAYMENT_TYPE, PAYMENT_AMOUNT, CLEARING_REASON, RECORD_UPDATED)
VALUES ('XBA00003000001', '000300000102', 1, TO_DATE('15-DEC-25','DD-MON-RR'), TO_DATE('15-DEC-25','DD-MON-RR'), 'R', 250, null, TO_DATE('15-DEC-25','DD-MON-RR'));


-- ============================================================================
-- 8. GTR_LP_REALLOCATION_OUT
--    PK: (GTR_REG_NUMBER, TIE_BREAKER)
-- ============================================================================

-- Column order: GTR_REG_NUMBER, TIE_BREAKER, REALLOCATION_DATE, REALLOCATION_TYPE, REALLOCATION_AMOUNT, REALLOCATION_EDP, CHARGE_REFERENCE, CHARGE_TYPE, RECORD_UPDATED

-- Actual repayment (type R, charge_type NULL)
INSERT INTO gtr_lp_reallocation_out (GTR_REG_NUMBER, TIE_BREAKER, CHARGE_TYPE, REALLOCATION_DATE, REALLOCATION_TYPE, REALLOCATION_AMOUNT, REALLOCATION_EDP, RECORD_UPDATED, CHARGE_REFERENCE)
VALUES ('XBA00003000001', 1, null, TO_DATE('01-AUG-25','DD-MON-RR'), 'R', -100, TO_DATE('01-AUG-25','DD-MON-RR'), TO_DATE('01-AUG-25','DD-MON-RR'), 'XB00003000C02');

INSERT INTO gtr_lp_reallocation_out (GTR_REG_NUMBER, TIE_BREAKER, CHARGE_TYPE, REALLOCATION_DATE, REALLOCATION_TYPE, REALLOCATION_AMOUNT, REALLOCATION_EDP, RECORD_UPDATED, CHARGE_REFERENCE)
VALUES ('XBA00003000001', 2, null, TO_DATE('15-JAN-26','DD-MON-RR'), 'R', -100, TO_DATE('15-JAN-26','DD-MON-RR'), TO_DATE('15-JAN-26','DD-MON-RR'), 'XB00003000C05');

-- Repayment interest repaid (type R, charge_type 'I')
INSERT INTO gtr_lp_reallocation_out (GTR_REG_NUMBER, TIE_BREAKER, CHARGE_TYPE, REALLOCATION_DATE, REALLOCATION_TYPE, REALLOCATION_AMOUNT, REALLOCATION_EDP, RECORD_UPDATED, CHARGE_REFERENCE)
VALUES ('XBA00003000001', 3, 'I', TO_DATE('01-SEP-25','DD-MON-RR'), 'R', -25, TO_DATE('01-SEP-25','DD-MON-RR'), TO_DATE('01-SEP-25','DD-MON-RR'), 'XB00003000C02');

-- Another actual repayment
INSERT INTO gtr_lp_reallocation_out (GTR_REG_NUMBER, TIE_BREAKER, CHARGE_TYPE, REALLOCATION_DATE, REALLOCATION_TYPE, REALLOCATION_AMOUNT, REALLOCATION_EDP, RECORD_UPDATED, CHARGE_REFERENCE)
VALUES ('XBA00003000001', 4, null, TO_DATE('15-FEB-26','DD-MON-RR'), 'R', -25, TO_DATE('15-FEB-26','DD-MON-RR'), TO_DATE('15-FEB-26','DD-MON-RR'), 'XB00003000C07');

-- Reallocation out (type O)
INSERT INTO gtr_lp_reallocation_out (GTR_REG_NUMBER, TIE_BREAKER, CHARGE_TYPE, REALLOCATION_DATE, REALLOCATION_TYPE, REALLOCATION_AMOUNT, REALLOCATION_EDP, RECORD_UPDATED, CHARGE_REFERENCE)
VALUES ('XBA00003000001', 5, null, TO_DATE('01-OCT-25','DD-MON-RR'), 'O', -150, TO_DATE('01-OCT-25','DD-MON-RR'), TO_DATE('01-OCT-25','DD-MON-RR'), 'XB00003000C02');

INSERT INTO gtr_lp_reallocation_out (GTR_REG_NUMBER, TIE_BREAKER, CHARGE_TYPE, REALLOCATION_DATE, REALLOCATION_TYPE, REALLOCATION_AMOUNT, REALLOCATION_EDP, RECORD_UPDATED, CHARGE_REFERENCE)
VALUES ('XBA00003000001', 6, null, TO_DATE('15-JAN-26','DD-MON-RR'), 'O', -150, TO_DATE('15-JAN-26','DD-MON-RR'), TO_DATE('15-JAN-26','DD-MON-RR'), 'XB00003000C05');


COMMIT;
